import type { Metadata } from "next";
import "./globals.css";
import { Inter, Noto_Sans } from 'next/font/google'
import Header from "@/components/Header";
 
const inter = Inter({ subsets: ['latin'] })
const notoSans = Noto_Sans({ subsets: ['latin'], variable: "--noto_sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${notoSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
